name: Update DevCard

on:
  push:
    branches: [ main ]

jobs:
  update-devcard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update DevCard
        uses: dailydotdev/action-devcard@2.3.1
        with:
          devcard_id: ${{ secrets.DEVCARD_ID }}
          commit_message: "chore: update devcard.svg"
